language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
# command to install dependencies
install:
  - "sudo apt-get update -qq"
  - "sudo apt-get install -y libdbus-1-dev"
  - "pip install ."
  - "pip install cython"
  - "pip install -r requirements.txt"
  - "./setup.py build"
# command to run tests
script: dbus-launch nosetests test
